spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mastery1
    username: postgres
    password: admin
  # Liquibase
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  # JPA properties
  jpa:
    show-sql: true
    open-in-view: false
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    com.godeltech.mastery.expertise.expertisemastery: debug
# Server configuration
server:
  port: 8083
